### PR TITLE
Upgrade redeyed to v0.5.0

### PR DESCRIPTION
**Pull request by trabus**
Upgrade to redeyed v0.5.0 for ES6 support. Added node 0.12 and io.js to `.travis.yml`

### CODE REVIEW

**Comment by thlorenz** [comment]
We need to update the [themes](https://github.com/thlorenz/cardinal/tree/master/themes) with this change. 
At a minimum the [default](https://github.com/thlorenz/cardinal/blob/master/themes/default.js) and [empty](https://github.com/thlorenz/cardinal/blob/master/themes/empty.js) configs need updating.

However updating other themes like [this one](https://github.com/thlorenz/cardinal/blob/master/themes/hide-semicolons.js) would be nice to keep things consistent.
Adding all ES6 keywords as `undefined` should suffice for now since in that case they'll pick up the color of their parent.

**Comment by trabus** [comment]
Okay, should have this shortly.

**Comment by thlorenz** [comment]
Take your time - won't get to this until tomorrow either way ;)

**Comment by trabus** [comment]
Not a problem. I'll be traveling to EmberConf tomorrow and won't be available most of the day. :)

**Comment by thlorenz** [comment]
Looks like this is good to go? (I'll remove the v0.9 test run from travis)

**Comment by trabus** [comment]
Yep, I was going to ask about 0.9, but if you're going to remove it, then great! :shipit:

**Comment by thlorenz** [comment]
Published as v0.5. Thanks.

**Pull request closed without merging**
