### PR TITLE
Add test folder to .npmignore

### PR DESCRIPTION
**Pull request by holtjohnson**
Making packages I use lighter. ;)

### CODE REVIEW

**Comment by derhuerst** [comment]
Why not use [the `files` field](https://docs.npmjs.com/files/package.json#files), which acts as a whitelist.

**Comment by holtjohnson** [comment]
There's not much of a difference, you can use either. It's a preference as to how you want to organize. Some people prefer the `files` field and some prefer a separate file.
I'll add the `files` field instead if that's your preference.

**Comment by derhuerst** [comment]
@holtjohnson I just think in most of the cases a whitelist is appropriate.

**Comment by holtjohnson** [comment]
Alright, I'll make the changes.

**Comment by thlorenz** [comment]
Please show that this makes a meaningful difference, i.e. only if the tarball is significantly smaller will I consider the pull, otherwise not since for some people working offline it is important to access the tests as part of the packages they installed locally on their machine.

You can compare the sizes as follows:

```sh
git checkout master
npm pack
du -h *.tgz

git checkout <your-branch>
npm pack
du -h *.tgz
```

**Comment by derhuerst** [comment]
@thlorenz It is common in the NPM ecosystem to exclude *everything* not related to the core functionality. Consider that [all those non-core files add up to terabytes of traffic](https://github.com/paulmillr/Array.prototype.findIndex/issues/11#issuecomment-66345652).

Developers can consult the GitHub repo for documentation, examples, build scripts anyway. They know how to do it. This whitelist is about users (who don't know/care about JS development), CI machines, etc.

Already today, supposedly lightweight NPM packages use >10mb because their deppendencies didn't care about a small footprint. And that is going to increase as NPM grows and dependency trees get deeper.

> […] otherwise not since for some people working offline it is important to access the tests as part of the packages they installed locally on their machine.

All those people can clone the git repo, install all dependencies and then work with that.

**Comment by holtjohnson** [comment]
The difference of the tarballs is 4K, but macs have a 4K filesystem block size (minimum file size) so the tests folder takes up 90K when extracted. I use it as a dependency of node-notifier.
I'm not familiar with this project so you would know best as to what people need. Just thought if it wasn't necessary it would lighten the load of users when using it as a NPM package. It will still be available to anyone who pulls this repo.

**Comment by thlorenz** [comment]
> tests folder takes up 90K when extracted

That's not huge and I'm more concerned about tarball size since that's what comes across the network. 4K is just not big enough to warrant not having tests available locally. Thanks, though.

**Comment by thlorenz** [comment]
> Consider that all those non-core files add up to terabytes of traffic.

Certainly true, but 4K just not that big of a deal even if cardinal installs a lot.
Compare this to just watching 1 second on netflix for instance ;)

**Comment by holtjohnson** [comment]
Alight, thanks for all your work!

**Pull request closed without merging**
